FROM ghcr.io/lizenzfass78851/ubuntu-xrdp:kali-light

RUN apt-get update && apt-get dist-upgrade -yy && \ 
  apt-get install -y \
  kali-linux-default && \
  apt-get autoremove -yy && \
  rm -rf /var/cache/apt /var/lib/apt/lists
